######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 7 17:17:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += video.qrc
