######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 20:40:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h msg.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp message.cpp
